# Taskfile for VTX1 project
# https://taskfile.dev

version: "3"

vars:
  PROJECT_NAME: "VTX1"
  DOCS_DIR: docs
  DIAGRAMS_DIR: "{{.DOCS_DIR}}/diagrams"
  WAVEFORMS_DIR: "{{.DOCS_DIR}}/waveforms"
  RELEASE_DIR: release
  OPENROAD_PATH: "D:/tools/OpenROAD"

set:
  - pipefail

tasks:
  default:
    cmds:
      - echo ""
      - echo "{{.PROJECT_NAME}} Build System"
      - echo ""
      - echo "Available tasks:"
      - echo "Task Name              Description"
      - echo "---------------------- -------------------------------------------------"
      - echo "PRIMARY TESTS:"
      - echo "  test-consolidated    Main comprehensive system test"
      - echo "  test-optimized       I2C-fixed optimized system test"
      - echo "  test-all             Run all test suites"
      - echo ""
      - echo "SPECIALIZED TESTS:"
      - echo "  test-microcode       Comprehensive microcode validation"
      - echo "  test-microcode-simple Quick microcode checks"
      - echo "  test-pipeline        CPU pipeline integration tests"
      - echo ""
      - echo "DEBUG & VALIDATION:"
      - echo "  test-status          Quick system status check"
      - echo "  test-i2c-fix         Validate I2C state machine fix"
      - echo ""
      - echo "SIMULATION:"
      - echo "  simulate             Interactive system simulation"
      - echo ""
      - echo "SYNTHESIS & VALIDATION:"
      - echo "  check                Syntax checking"
      - echo "  synth                Synthesize design"
      - echo ""
      - echo "UTILITIES:"
      - echo "  clean                Clean build artifacts"
      - echo "  doc                  Generate documentation"
      - echo "  install              Install development tools"
    silent: true

  # Primary Test Tasks
  test-consolidated:
    desc: Test complete VTX1 consolidated system
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Testing VTX1 Consolidated System..."
      - iverilog -g2012 -I src/common -I src/cpu -I src/memory -I src/system -I src/cache -I src/testbench -o build/vtx1_consolidated_test src/vtx1_top_consolidated.v src/testbench/tb_vtx1_consolidated.v src/common/*.v src/cpu/*.v src/memory/*.v src/system/*.v src/cache/*.v
      - vvp build/vtx1_consolidated_test
      - echo "VTX1 Consolidated system test completed. View waveforms with gtkwave vtx1_consolidated_test.vcd"

  test-optimized:
    desc: "Run optimized consolidated system test with I2C state fix"
    cmds:
      - powershell -Command "Remove-Item build\* -Force -ErrorAction SilentlyContinue"
      - powershell -Command "New-Item -ItemType Directory -Path build -Force | Out-Null"
      - echo "Compiling VTX1 system with I2C state machine fixes..."
      - powershell -Command "iverilog -I src\common -I src\cache -o build\vtx1_optimized_test src\vtx1_top_consolidated.v src\testbench\tb_vtx1_consolidated.v src\common\*.v src\cpu\*.v src\memory\*.v src\system\*.v src\cache\*.v"
      - powershell -Command "if ($LASTEXITCODE -eq 0) { Write-Host 'Running optimized test with I2C fixes...' -ForegroundColor Green; .\build\vtx1_optimized_test } else { Write-Host 'Compilation failed' -ForegroundColor Red }"

  test-all:
    desc: Run all VTX1 tests
    cmds:
      - task: test-microcode-simple
      - task: test-pipeline
      - task: test-optimized
      - echo "All VTX1 tests completed successfully"

  # Specialized Test Tasks
  test-microcode:
    desc: Test microcode system with comprehensive validation
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Testing microcode system..."
      - iverilog -I src/common -I src/cpu -I src/system -I src/testbench -o build/microcode_test src/testbench/tb_microcode_system.v src/cpu/*.v src/common/*.v src/system/*.v
      - vvp build/microcode_test
      - echo "Microcode system tests completed. View waveforms with gtkwave microcode_test.vcd"

  test-microcode-simple:
    desc: Quick microcode validation tests
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Running simple microcode tests..."
      - iverilog -g2012 -I src/common -I src/cpu -I src/testbench -o build/microcode_simple_test src/testbench/tb_microcode_simple.v src/cpu/*.v src/common/*.v
      - vvp build/microcode_simple_test
      - echo "Simple microcode tests completed. View waveforms with gtkwave microcode_simple_test.vcd"

  test-pipeline:
    desc: Test CPU pipeline integration and performance
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Testing CPU pipeline integration..."
      - iverilog -g2012 -I src/common -I src/cpu -I src/testbench -o build/pipeline_test src/testbench/test_integrated_pipeline.v src/cpu/*.v src/common/*.v
      - vvp build/pipeline_test
      - echo "CPU pipeline tests completed. View waveforms with gtkwave pipeline_test.vcd"

  # Debug and Issue Resolution Tasks
  test-i2c-fix:
    desc: Test I2C controller state machine fix
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Testing I2C controller with fixed state constants..."
      - iverilog -g2012 -I src/common -o build/i2c_fix_test src/system/i2c_controller.v src/common/vtx1_state_constants.v src/common/vtx1_error_macros.v src/common/ternary_*.v src/common/vtx1_clock_divider.v
      - echo "I2C controller compilation successful - state constants fixed"

  test-status:
    desc: "Quick system status check and Error LED validation"
    cmds:
      - echo "=== VTX1 System Status Check ==="
      - echo "Available testbenches:"
      - powershell -Command "Get-ChildItem src\testbench\*.v | Select-Object Name, Length | Format-Table -AutoSize"
      - echo "Running quick consolidated test..."
      - task: test-optimized

  # Simulation
  simulate:
    desc: Interactive simulation with GTKWave
    cmds:
      - task: test-consolidated
      - gtkwave vtx1_consolidated_test.vcd

  # Synthesis & Validation
  check:
    desc: Check VTX1 consolidated system syntax
    cmds:
      - echo "Checking VTX1 Consolidated System syntax..."
      - iverilog -g2012 -I src/common -I src/cpu -I src/memory -I src/system -t null src/vtx1_top_consolidated.v src/common/*.v src/cpu/*.v src/memory/*.v src/system/*.v src/cache/*.v
      - echo "VTX1 Consolidated syntax check completed"

  synth:
    desc: Synthesize VTX1 consolidated design with Yosys
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path build | Out-Null"
      - echo "Synthesizing VTX1 Consolidated System..."
      - yosys -p "read_verilog -I src/common -I src/cpu -I src/memory -I src/system -I src/cache src/vtx1_top_consolidated.v src/common/ternary_arithmetic.v src/common/ternary_constants.v src/common/vtx1_state_constants.v src/common/vtx1_interfaces.v src/common/vtx1_error_macros.v src/common/ternary_logic.v src/common/ternary_encoding.v src/cpu/instruction_decoder.v src/cpu/hazard_detection.v src/cpu/microcode_rom.v src/cpu/forwarding_unit.v src/cpu/microcode_sequencer.v src/cpu/cpu_core.v src/cpu/tcu_enhanced_interface.v src/cpu/register_file.v src/memory/memory_controller.v src/system/uart_controller.v src/system/spi_controller.v src/system/i2c_controller.v src/system/gpio_controller.v src/system/dma_controller.v src/system/debug_controller.v src/system/cpu_adapter.v src/system/bus_matrix.v src/cache/cache_controller.v; synth -top vtx1_top_consolidated; write_verilog build/vtx1_consolidated_synth.v; write_json build/vtx1_consolidated_synth.json"
      - echo "VTX1 Consolidated synthesis completed. Output in build/vtx1_consolidated_synth.v"

  # Utilities
  clean:
    desc: Clean build artifacts
    cmds:
      - powershell -Command "Remove-Item -Recurse -Force -Path build -ErrorAction SilentlyContinue"
      - powershell -Command "Remove-Item -Force -Path *.vcd -ErrorAction SilentlyContinue"
      - powershell -Command "Remove-Item -Force -Path *.out -ErrorAction SilentlyContinue"
      - echo "Build artifacts cleaned"

  doc:
    desc: Generate documentation in PDF
    cmds:
      - echo "Generating documentation..."
      - asciidoctor-pdf --theme docs/ARCHITECTURE.yml -r asciidoctor-diagram -o "{{.RELEASE_DIR}}/vtx1l-architecture.pdf" docs/ARCHITECTURE.adoc
      - echo "Documentation generated in {{.RELEASE_DIR}}"

  install:
    desc: Install required tools
    cmds:
      - echo "Installing development tools..."
      - scoop install iverilog
      - scoop install yosys
      - echo "Installing Asciidoctor documentation tools..."
      - scoop install ruby msys2
      - ridk install 3
      - gem install asciidoctor asciidoctor-pdf asciidoctor-diagram rouge bigdecimal
      - npm install -g @mermaid-js/mermaid-cli
      - npm install -g wavedrom-cli
      - npm install -g bytefield-svg
      - echo "All tools installed successfully."
    silent: false
